#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

TEMPDIR=/tmp/podman-static
ADD_ARGS=${ADD_ARGS:-}
URL=${URL:-https://podman.k8s.saschagrunert.de/assets}
container=${container:-}

if [[ -n $container ]]; then
    ADD_ARGS="--storage-driver=vfs"
fi

if [[ ! -d $TEMPDIR ]]; then
    mkdir -p $TEMPDIR

    export REGISTRIES_CONFIG_PATH=$TEMPDIR/registries.conf
    echo 'unqualified-search-registries = ["docker.io", "quay.io"]' \
        >"$REGISTRIES_CONFIG_PATH"

    export SIGNATURE_POLICY_PATH=$TEMPDIR/policy.json
    echo '{ "default": [{ "type": "insecureAcceptAnything" }] }' \
        >"$SIGNATURE_POLICY_PATH"

    export CNI_DEFAULT_NETWORK=podman

    export CNI_CONFIG_DIR=$TEMPDIR/net.d
    mkdir -p "$CNI_CONFIG_DIR"
    cat <<EOT >>"$CNI_CONFIG_DIR/87-podman-bridge.conflist"
{
  "cniVersion": "0.4.0",
  "name": "podman",
  "plugins": [
    {
      "type": "bridge",
      "bridge": "cni-podman0",
      "isGateway": true,
      "ipMasq": false,
      "ipam": {
        "type": "host-local",
        "routes": [{ "dst": "0.0.0.0/0" }],
        "ranges": [[{ "subnet": "10.88.0.0/16", "gateway": "10.88.0.1" }]]
      }
    },
    { "type": "portmap", "capabilities": { "portMappings": true } },
    { "type": "tuning" }
  ]
}
EOT

    export CNI_PLUGIN_DIR=$TEMPDIR/plugins
    mkdir -p "$CNI_PLUGIN_DIR"

    curl "$URL/bridge" -o "$CNI_PLUGIN_DIR/bridge"
    chmod +x "$CNI_PLUGIN_DIR/bridge"

    curl "$URL/portmap" -o "$CNI_PLUGIN_DIR/portmap"
    chmod +x "$CNI_PLUGIN_DIR/portmap"

    curl "$URL/host-local" -o "$CNI_PLUGIN_DIR/host-local"
    chmod +x "$CNI_PLUGIN_DIR/host-local"

    curl "$URL/tuning" -o "$CNI_PLUGIN_DIR/tuning"
    chmod +x "$CNI_PLUGIN_DIR/tuning"

    curl "$URL/conmon" -o "$TEMPDIR/conmon"
    chmod +x "$TEMPDIR/conmon"

    curl "$URL/runc" -o "$TEMPDIR/runc"
    chmod +x "$TEMPDIR/runc"

    curl "$URL/podman" -o "$TEMPDIR/podman"
    chmod +x "$TEMPDIR/podman"
fi

"$TEMPDIR/podman" \
    --runtime "$TEMPDIR/runc" \
    --conmon "$TEMPDIR/conmon" \
    --cgroup-manager cgroupfs \
    $ADD_ARGS \
    "$@"
