#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

TEMPDIR=/tmp/podman-static
ADD_ARGS=${ADD_ARGS:-}
container=${container:-}

if [[ -n $container ]]; then
    ADD_ARGS="--storage-driver=vfs"
fi

export REGISTRIES_CONFIG_PATH=$TEMPDIR/registries.conf
export SIGNATURE_POLICY_PATH=$TEMPDIR/policy.json
export CNI_DEFAULT_NETWORK=podman
export CNI_CONFIG_DIR=$TEMPDIR/net.d
export CNI_PLUGIN_DIR=$TEMPDIR/plugins

if [[ ! -d $TEMPDIR ]]; then
    echo "Preparing $TEMPDIR, which will be re-used in future calls"
    mkdir -p $TEMPDIR

    echo 'unqualified-search-registries = ["docker.io", "quay.io"]' \
        >"$REGISTRIES_CONFIG_PATH"

    echo '{ "default": [{ "type": "insecureAcceptAnything" }] }' \
        >"$SIGNATURE_POLICY_PATH"

    mkdir -p "$CNI_CONFIG_DIR"
    cat <<EOT >>"$CNI_CONFIG_DIR/87-podman-bridge.conflist"
{
  "cniVersion": "0.4.0",
  "name": "podman",
  "plugins": [
    {
      "type": "bridge",
      "bridge": "cni-podman0",
      "isGateway": true,
      "ipMasq": false,
      "ipam": {
        "type": "host-local",
        "routes": [{ "dst": "0.0.0.0/0" }],
        "ranges": [[{ "subnet": "172.88.0.0/16", "gateway": "172.88.0.1" }]]
      }
    },
    { "type": "portmap", "capabilities": { "portMappings": true } },
    { "type": "tuning" }
  ]
}
EOT

    mkdir -p "$CNI_PLUGIN_DIR"

    echo "Downloading assets…"
    declare -A VERSIONS=(
        ["cni-plugins"]=v0.8.5
        ["conmon"]=v2.0.15
        ["runc"]=v1.0.0-rc10
    )
    curl_to() {
        curl -sfL -o "$1" "$2"
    }
    curl_to "$TEMPDIR/conmon" \
        https://github.com/containers/conmon/releases/download/"${VERSIONS["conmon"]}"/conmon &
    curl_to - \
        https://github.com/containernetworking/plugins/releases/download/"${VERSIONS["cni-plugins"]}"/cni-plugins-linux-amd64-"${VERSIONS["cni-plugins"]}".tgz |
        tar xfz - -C "$CNI_PLUGIN_DIR" &
    curl_to "$TEMPDIR/runc" \
        https://github.com/opencontainers/runc/releases/download/"${VERSIONS["runc"]}"/runc.amd64 &
    curl_to "$TEMPDIR/podman" https://podman.k8s.saschagrunert.de/podman &

    wait

    chmod +x "$TEMPDIR/conmon"
    chmod +x "$TEMPDIR/podman"
    chmod +x "$TEMPDIR/runc"
fi

"$TEMPDIR/podman" \
    --runtime "$TEMPDIR/runc" \
    --conmon "$TEMPDIR/conmon" \
    --cgroup-manager cgroupfs \
    $ADD_ARGS \
    "$@"
